In [8]:
import numpy as np

arr = np.array([8,45,25,41,63,47,52,4,85,65])

print("Original Array")
print(arr)

print("\nNumbers greater than 25")
print(arr[arr > 25])

even_numbers = arr[arr% 2 == 0]

print("\nEven numbers")
print(even_numbers)

print("\nOdd numbers")
odd_numbers = arr[arr% 2 != 0]
print(odd_numbers)

Original Array
[ 8 45 25 41 63 47 52  4 85 65]

Numbers greater than 25
[45 41 63 47 52 85 65]

Even numbers
[ 8 52  4]

Odd numbers
[45 25 41 63 47 85 65]
