In [1]:
# Full Array

import numpy as np

arr = np.full((3,3), 5)

print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [2]:
# Arrange

arr = np.arange(1,11)

print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# LineSpace

arr = np.linspace(0,10,5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [7]:
# Random Number

arr = np.random.randint(1,100,10)

print(arr)

[84 57 39 84 94 34 13 85 77  6]
