In [1]:
import numpy as np

print("=" * 50)
print("     STUDENT PERFORMANCE ANALYTICS SYSTEM")
print("=" * 50)

marks = np.random.randint(40, 101, 20)

print("\nMarks of Students:")
print(marks)

highest = np.max(marks)
lowest = np.min(marks)
average = np.mean(marks)
median = np.median(marks)
std_dev = np.std(marks)
variance = np.var(marks)

passed = np.sum(marks >= 40)
failed = np.sum(marks < 40)

A_plus = np.sum(marks >= 90)

A = np.sum((marks >= 80) & (marks < 90))

B = np.sum((marks >= 70) & (marks < 80))

C = np.sum((marks >= 60) & (marks < 70))

D = np.sum((marks >= 40) & (marks < 60))

top_students = marks[marks >= 90]

weak_students = marks[marks < 60]

print("\n" + "=" * 50)
print("            PERFORMANCE REPORT")
print("=" * 50)

print(f"Total Students           : {len(marks)}")
print(f"Highest Marks            : {highest}")
print(f"Lowest Marks             : {lowest}")

print(f"Average Marks            : {average:.2f}")
print(f"Median Marks             : {median}")

print(f"Standard Deviation       : {std_dev:.2f}")
print(f"Variance                 : {variance:.2f}")

print("\nPASS / FAIL ANALYSIS")
print("-" * 30)

print(f"Passed Students          : {passed}")
print(f"Failed Students          : {failed}")

print("\nGRADE DISTRIBUTION")
print("-" * 30)

print(f"A+ Grade (90-100)        : {A_plus}")
print(f"A Grade  (80-89)         : {A}")
print(f"B Grade  (70-79)         : {B}")
print(f"C Grade  (60-69)         : {C}")
print(f"D Grade  (40-59)         : {D}")

print("\nTOP PERFORMERS (>=90)")
print("-" * 30)
print(top_students)

print("\nWEAK PERFORMERS (<60)")
print("-" * 30)
print(weak_students)

print("\nSTUDENTS SCORING ABOVE AVERAGE")
print("-" * 30)
print(marks[marks > average])

print("\n" + "=" * 50)
print("         ANALYSIS COMPLETED")
print("=" * 50)


     STUDENT PERFORMANCE ANALYTICS SYSTEM

Marks of Students:
[100  96  73  65  75  96  94  53  53  96  40  90  57  86  87  81  47  68
  98  43]

            PERFORMANCE REPORT
Total Students           : 20
Highest Marks            : 100
Lowest Marks             : 40
Average Marks            : 74.90
Median Marks             : 78.0
Standard Deviation       : 19.80
Variance                 : 392.09

PASS / FAIL ANALYSIS
------------------------------
Passed Students          : 20
Failed Students          : 0

GRADE DISTRIBUTION
------------------------------
A+ Grade (90-100)        : 7
A Grade  (80-89)         : 3
B Grade  (70-79)         : 2
C Grade  (60-69)         : 2
D Grade  (40-59)         : 6

TOP PERFORMERS (>=90)
------------------------------
[100  96  96  94  96  90  98]

WEAK PERFORMERS (<60)
------------------------------
[53 53 40 57 47 43]

STUDENTS SCORING ABOVE AVERAGE
------------------------------
[100  96  75  96  94  96  90  86  87  81  98]

         ANALYSIS COMPLE