In [9]:
import numpy as np

arr1 = np.array([[4,7],[8,9]])
print("First matrix :", arr1)

arr2 = np.array([[5,6],[9,3]])
print("Second matrix :", arr2)


print("\nSum of both matrix : ")
print(arr1+arr2)

print("\nMatrix Multiplication :")
print(np.dot(arr1,arr2))

print("\nTranspose of first matrix is :")
print(arr1.T)

First matrix : [[4 7]
 [8 9]]
Second matrix : [[5 6]
 [9 3]]

Sum of both matrix : 
[[ 9 13]
 [17 12]]

Matrix Multiplication :
[[ 83  45]
 [121  75]]

Transpose of first matrix is :
[[4 8]
 [7 9]]
