In [2]:
#Zero Arrays

import numpy as np

arr = np.zeros((4,4))

print("Zero Array of 4 * 4 matrix : ")
print(arr)

Zero Array of 4 * 4 matrix : 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
