In [6]:
import numpy as np

arr = np.array([8,5,4,2,45,1,20])
print("Add 5 to every element")
print(arr+5)

print("\nMultiply every element by 3")
print(arr*3)

print("\nSquare every element")
print(arr**2)

Add 5 to every element
[13 10  9  7 50  6 25]

Multiply every element by 3
[ 24  15  12   6 135   3  60]

Square every element
[  64   25   16    4 2025    1  400]
