In [1]:
#1-D Array

import numpy as np

arr = np.array([10 , 20 , 30 , 40 , 50])

print(arr)

[10 20 30 40 50]


In [2]:
#2-D Array

import numpy as np

arr = np.array([
    [1,5,6],
    [2,5,6]
])

print(arr)

[[1 5 6]
 [2 5 6]]


In [16]:
# Array Properties

arr = np.array([
        [1,2,3,4],
        [6,4,5,8]
])

print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(2, 4)
8


In [4]:
# Array Indexing

arr = np.array([10,20,30,40])

print(arr[0])
print(arr[-1])

10
40


In [5]:
#Array Slicing

print(arr[1:3])

[20 30]


In [6]:
# Array Operations

arr = np.array([1,2,3,4])

print(arr + 10)
print(arr * 2)
print(arr ** 2)

[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]


In [15]:
# Array Reshape

arr = np.array([1,2,3,4,5,6])

print(arr.reshape(3,2))
print("\n")
print( arr.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]


[[1 2 3]
 [4 5 6]]
