In [14]:
# Center Element of 3*3 Matrix

import numpy as np

arr = np.array([
    [2,5,4],
    [5,6,4],
    [9,3,7]
])
print(arr)

print("\n Center Element of 3*3 Matrix is :")
print(arr[1,1])

print("\n First three element of this matrix is :")
print(arr[0:1])

print("\n last three element of this matrix is :")
print(arr[-1])

[[2 5 4]
 [5 6 4]
 [9 3 7]]

 Center Element of 3*3 Matrix is :
6

 First three element of this matrix is :
[[2 5 4]]

 last three element of this matrix is :
[9 3 7]
